/**
 * feedback.js — Real-time feedback display + Audio coaching
 *
 * TTS STRATEGY (two-tier):
 *  ① Pre-synthesized audio files (Coqui XTTS v2 — realistic voice)
 *    Generated by: tts-server/generate_voices.py
 *    Stored in:    assets/voices/<CODE>.wav
 *    Latency:      ~0ms (just plays an Audio element)
 *
 *  ② Web Speech API fallback (browser built-in)
 *    Used when: audio file not found, or generator hasn't been run
 *    Latency:   ~100ms, robotic but functional
 *
 * The browser auto-detects which tier is available by checking the manifest.
 */

const SPEECH_COOLDOWN_MS = 4000; // Don't repeat same cue within this window
const VOICES_MANIFEST    = 'assets/voices/manifest.json';

export class FeedbackManager {
  constructor({ feedbackEl, repCountEl, repQualityEl, angleDebugEl }) {
    this.feedbackEl   = feedbackEl;
    this.repCountEl   = repCountEl;
    this.repQualityEl = repQualityEl;
    this.angleDebugEl = angleDebugEl;

    this._lastMessages  = new Set();
    this._qualityTimer  = null;
    this._lastRepCount  = 0;

    // Audio state
    this._ttsEnabled    = true;
    this._lastSpoken    = new Map();  // code/text → timestamp
    this._ttsUnlocked   = false;
    this._audioCache    = new Map();  // code → HTMLAudioElement
    this._manifest      = null;       // loaded from manifest.json
    this._manifestReady = false;

    this._loadManifest();
  }

  // ─── Setup ──────────────────────────────────────────────────────────────────

  /** Try to load the pre-synthesized voice manifest. */
  async _loadManifest() {
    try {
      const res = await fetch(VOICES_MANIFEST);
      if (res.ok) {
        this._manifest = await res.json();
        this._manifestReady = true;
        console.log('[FormAI TTS] Loaded pre-synthesized voices ✓');
      }
    } catch {
      console.log('[FormAI TTS] No pre-synthesized voices found — using Web Speech API fallback.');
    }
  }

  /**
   * Call on "Start Workout" button click to unlock audio on iOS.
   * iOS Safari blocks Audio.play() until a user gesture has occurred.
   */
  unlockTTS() {
    if (this._ttsUnlocked) return;
    this._ttsUnlocked = true;
    // Play a silent buffer to unlock Web Audio context on iOS
    const ctx = new (window.AudioContext || window.webkitAudioContext)();
    const buf = ctx.createBuffer(1, 1, 22050);
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.connect(ctx.destination);
    src.start(0);
    ctx.close();
  }

  setTTSEnabled(enabled) {
    this._ttsEnabled = enabled;
    if (!enabled) {
      window.speechSynthesis?.cancel();
      document.querySelectorAll('.formai-audio').forEach(a => { a.pause(); a.currentTime = 0; });
    }
  }

  // ─── Public API ──────────────────────────────────────────────────────────────

  /**
   * Update everything from an exercise analysis result.
   * @param {AnalysisResult} result
   */
  update(result) {
    this._updateFeedback(result.formIssues);
    this._updateRepCount(result.repCount);
    if (result.repQuality) {
      this._flashRepQuality(result.repQuality);
    }
    if (this.angleDebugEl && result.angleData) {
      this._updateAngleDebug(result.angleData);
    }
    this._speakTopIssue(result.formIssues);
  }

  showSetupStatus(checks) {
    if (!this.feedbackEl) return;
    this.feedbackEl.innerHTML = checks.map(c => `
      <div class="setup-check ${c.passed ? 'passed' : 'failed'}">
        <span class="check-icon">${c.passed ? '✓' : '○'}</span>
        <div>
          <div class="check-label">${c.label}</div>
          <div class="check-hint">${c.hint}</div>
        </div>
      </div>
    `).join('');
  }

  /** Play a one-off announcement (session start, rep milestone, etc.) */
  announce(text, code = null) {
    this._play(text, code, true);
  }

  clear() {
    if (this.feedbackEl) this.feedbackEl.innerHTML = '';
    if (this.repQualityEl) this.repQualityEl.style.opacity = '0';
    this._lastMessages  = new Set();
    this._lastRepCount  = 0;
    window.speechSynthesis?.cancel();
    this._audioCache.forEach(a => { a.pause(); a.currentTime = 0; });
  }

  // ─── Private: Display ────────────────────────────────────────────────────────

  _updateFeedback(issues = []) {
    if (!this.feedbackEl) return;
    const messages = issues.map(i => i.message);
    const msgSet   = new Set(messages);
    if (this._setsEqual(msgSet, this._lastMessages)) return;
    this._lastMessages = msgSet;

    if (messages.length === 0) {
      this.feedbackEl.innerHTML = `
        <div class="feedback-good">
          <span class="feedback-icon">✓</span>
          <span>Great form! Keep going.</span>
        </div>`;
      return;
    }

    this.feedbackEl.innerHTML = messages.map(msg => `
      <div class="feedback-item">
        <span class="feedback-icon">⚠</span>
        <span>${msg}</span>
      </div>
    `).join('');
  }

  _updateRepCount(count) {
    if (!this.repCountEl || count === this._lastRepCount) return;
    this.repCountEl.textContent = count;
    this.repCountEl.classList.remove('rep-bounce');
    void this.repCountEl.offsetWidth;
    this.repCountEl.classList.add('rep-bounce');

    // Milestone announcements
    if (count > 0 && count % 5 === 0) {
      this.announce(`${count} reps! Keep it up!`, `REPS_${count}`);
    } else if (count > 0) {
      // Just a short beep or silent for non-milestone reps (don't speak every rep)
    }
    this._lastRepCount = count;
  }

  _flashRepQuality(quality) {
    if (!this.repQualityEl) return;
    if (this._qualityTimer) clearTimeout(this._qualityTimer);

    const labels  = { good: '🔥 Good Rep!', fair: '👍 Fair Rep', poor: '⚠ Poor Form' };
    const classes = { good: 'quality-good', fair: 'quality-fair', poor: 'quality-poor' };
    const codes   = { good: 'REP_GOOD', fair: 'REP_FAIR', poor: 'REP_POOR' };
    const speech  = { good: 'Good rep!', fair: 'Fair rep.', poor: 'Work on your form.' };

    this.repQualityEl.textContent   = labels[quality]  || '';
    this.repQualityEl.className     = `rep-quality ${classes[quality] || ''}`;
    this.repQualityEl.style.opacity = '1';

    // Announce rep quality
    this.announce(speech[quality], codes[quality]);

    this._qualityTimer = setTimeout(() => {
      this.repQualityEl.style.opacity = '0';
    }, 2200);
  }

  _updateAngleDebug(angleData) {
    if (!this.angleDebugEl) return;
    this.angleDebugEl.textContent = Object.entries(angleData)
      .map(([k, v]) => `${k}: ${v}°`)
      .join('  |  ');
  }

  // ─── Private: Audio ──────────────────────────────────────────────────────────

  _speakTopIssue(issues = []) {
    if (!this._ttsEnabled || issues.length === 0) return;

    // Sort: errors first, then warnings
    const sorted = [...issues].sort((a, b) =>
      (a.severity === 'error' ? 0 : 1) - (b.severity === 'error' ? 0 : 1)
    );
    const top = sorted[0];

    const key = top.code || top.message;
    const lastTime = this._lastSpoken.get(key) ?? 0;
    if (Date.now() - lastTime < SPEECH_COOLDOWN_MS) return;

    this._lastSpoken.set(key, Date.now());
    this._play(top.message, top.code, false);
  }

  /**
   * Play audio for a given text/code.
   * Tries pre-synthesized file first, falls back to Web Speech API.
   *
   * @param {string}  text      - Text to speak
   * @param {string|null} code  - Issue code for looking up WAV file
   * @param {boolean} interrupt - Whether to interrupt currently playing audio
   */
  _play(text, code = null, interrupt = false) {
    if (!this._ttsEnabled) return;

    // ── Tier 1: Pre-synthesized audio (Coqui XTTS) ──────────────────────────
    if (this._manifestReady && code && this._manifest?.[code]) {
      this._playFile(this._manifest[code], interrupt);
      return;
    }

    // ── Tier 2: Web Speech API fallback ─────────────────────────────────────
    this._speakWebAPI(text, interrupt);
  }

  _playFile(path, interrupt = false) {
    if (interrupt) {
      // Stop any currently playing pre-synthesized audio
      this._audioCache.forEach(a => { if (!a.paused) { a.pause(); a.currentTime = 0; } });
      window.speechSynthesis?.cancel();
    } else {
      // Don't play if something is already playing
      let isPlaying = false;
      this._audioCache.forEach(a => { if (!a.paused) isPlaying = true; });
      if (isPlaying || window.speechSynthesis?.speaking) return;
    }

    // Get or create cached Audio element
    let audio = this._audioCache.get(path);
    if (!audio) {
      audio = new Audio(path);
      audio.className = 'formai-audio';
      this._audioCache.set(path, audio);
    }

    audio.currentTime = 0;
    audio.play().catch(e => {
      // If file play fails, fall back to Web Speech API
      console.warn('[FormAI TTS] Audio file play failed, using fallback:', e.message);
      this._speakWebAPI(null, interrupt);
    });
  }

  _speakWebAPI(text, interrupt = false) {
    if (!window.speechSynthesis || !text) return;

    if (interrupt) {
      window.speechSynthesis.cancel();
    } else if (window.speechSynthesis.speaking) {
      return; // Don't queue — drop to avoid backlog
    }

    const u = new SpeechSynthesisUtterance(text);
    u.rate   = 1.05;
    u.pitch  = 1.0;
    u.volume = 1.0;

    // Prefer a local voice for lower latency
    const voices    = window.speechSynthesis.getVoices();
    const preferred = voices.find(v => v.localService && v.lang.startsWith('en'));
    if (preferred) u.voice = preferred;

    window.speechSynthesis.speak(u);
  }

  // ─── Utils ───────────────────────────────────────────────────────────────────

  _setsEqual(a, b) {
    if (a.size !== b.size) return false;
    for (const v of a) if (!b.has(v)) return false;
    return true;
  }
}
